# -*- coding: utf-8 -*-
"""1st-prlimanry-task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XV9lOmk2ednmf-jGa4LPsaqZMZJbqNf

AI Question 1
"""

import numpy as np

data = np.array([
    [170, 65, 19, 85, 5],
    [180, 75, 20, 90, 6],
    [160, 55, 18, 80, 4],
    [175, 70, 21, 88, 7],
    [155, 50, 19, 82, 5],
    [165, 62, 22, 89, 6],
    [178, 80, 23, 91, 7],
    [162, 58, 20, 78, 3],
    [172, 68, 19, 86, 5],
    [169, 66, 20, 84, 4],
    [171, 64, 22, 87, 6],
    [177, 72, 21, 90, 9],
    [174, 76, 24, 88, 8],
    [158, 52, 18, 75, 3],
    [164, 63, 19, 81, 4]
])

print("Student S.No \tHeight\tWeight\tAge\tAvg Grade\tCourses")
for index, student in enumerate(data):
    print(f"Student {index + 1}\t{student[0]}\t{student[1]}\t{student[2]}\t{student[3]}\t\t{student[4]}")

"""question 1.1"""

height = []

for i in range(0, len(data), 1):
  height.append(data[i,0])

print(height)
print(len(height))

avg_height = sum(height) / len(height)

print(f"the average height of all the students is {avg_height}")

"""Question 1.2"""

age = []

for a in range(0, len(data), 1):
  age.append(data[a, 2])

print(age)

max_age = max(age)

print(f"the maximum age of the students is {max_age}")

"""Question 1.3"""

courses = []

for c in range(0, len(data), 1):
  courses.append(data[c, 4])

print(courses)

max_courses = max(courses)

print(f"the maximum no of courses taken by the students is {max_courses}")

"""Question 1.4"""

count = 0

avg_grade = []

for g in range(0, len(data), 1):
  avg_grade.append(data[g, 3])
  grade = data[g, 3]
  if grade >= 85:
    count += 1

print(avg_grade)
print(count)

"""Question 1.5"""

age_grade_ratio = np.divide(age ,avg_grade)

print(age_grade_ratio)